### ISSUE TITLE
Cannot install on Julia 1.10

### ISSUE THREAD

**Issue by gdkrmr** [tecosaur/About.jl#10]
Compatibility is restricted to `InteractiveUtils 1.11` and therefore Julia 1.11. Is there a reason for this?

**Comment by tecosaur** [comment]
Currently it requires `StyledStrings`, the new 1.11 stdlib. A compat release for `StyledStrings` is planned, at which point the version requirements here can be relaxed.

**Comment by tecosaur** [comment]
Works with Julia 1.9+ as of 99ba351192f956e4fd19077231cb59bcccb84a4e, just with an awful load-time cost :sweat_smile:
