### ISSUE TITLE
Register the package

### ISSUE THREAD

**Issue by carstenbauer** [tecosaur/About.jl#16]
Any reason this isn't registered in General yet?

**Comment by tecosaur** [comment]
Until yesterday it was unregisterable as a consequence of `JuliaSyntaxHighlighting` being unregistered (which changes yesterday).

I'm currently thinking I'll do a little polish (I'd like to do more with strings and `Memory` specifically, I'm also wondering if I want to try showing how the type tag shows up, if possible), then register (v0.1 or v1.0, I haven't decided which) :slightly_smiling_face:

**Comment by tecosaur** [comment]
It's now being registered, try it in 3 days.
