### ISSUE TITLE
`about(:abc)` told me to file an issue

### ISSUE THREAD

**Issue by miguelraz** [tecosaur/About.jl#18]
so here it is 😄

**Comment by tecosaur** [comment]
Thanks Miguel! For anyone curious and my own reference when I sit down to look at this, what's going on is due to the interning of Symbols, the interned value takes up N bytes but instances of the symbol don't. More specifically, `Base.summarysize` reports 0, but I don't think that's quite right.

```
julia> about(:abc)
Symbol (mutable) (<: Any)
 Memory footprint: 3B directly (! referencing 0B in total, strangely less than the direct, please open an issue on About.jl with this example)
```

**Comment by tecosaur** [comment]
New output:
```julia-repl
julia> about(:abc)
Symbol (<: Any), an 8B reference to a 3B interned string
```

**Comment by miguelraz** [comment]
Beautiful! 👨🏾‍🍳 💋
