### ISSUE TITLE
`about` mentions non-existing names

### ISSUE THREAD

**Issue by matthias314** [tecosaur/About.jl#28]
I've tried out About.jl on my package [LinearCombinations.jl](https://github.com/matthias314/LinearCombinations.jl). The output of `about(LinearCombinations)` contains the lines
```
Re-exports 1 name (from Core):
• swap
```
The package does indeed export `swap`. However, as far as I can tell, there is no `Core.swap`. Is this a bug?

I'm using About v1.0.0, LinearCombinations v0.4.1, Julia v1.10.4.

**Comment by tecosaur** [comment]
Thanks for the issue! Fixed in db9cbce4c7bc7ad5c59f07bd30be6f4556dc4635 :slightly_smiling_face:
