### ISSUE TITLE
`about(typemin(Int))` prints an unnecessary negative sign

### ISSUE THREAD

**Issue by eikopf** [tecosaur/About.jl#31]
The bug is fairly simple: for all the `Int` types, `about` prints an extra `-` for their minimum values.

```julia-repl
julia> about(typemin(Int8))
10000000 = --128

julia> about(typemin(Int64))
1000000000000000000000000000000000000000000000000000000000000000
 = --9223372036854775808
```

Seems like an easy fix? This is basically just a QOL issue.

**Comment by eikopf** [comment]
The issue is in [this line](https://github.com/tecosaur/About.jl/blob/2c0cb43d0e3b52d51b5dcc616a6cbf960d8bf3af/src/values.jl#L242) --- the `abs` function has documented overflow behaviour for the `typemin` of signed values.

> __From `? abs`__
>
> When `abs` is applied to signed integers, overflow may occur, resulting in the return of a negative value. This overflow occurs only when `abs` is applied to the minimum representable value of a signed integer. That is, when `x == typemin(typeof(x)), abs(x) == x < 0`, not `-x` as might be expected.

**Comment by GunnarFarneback** [comment]
An alternative to widening the type is to strip the sign from the string representation.
```
absvaluestr = lstrip(string(value), '-')
```
(More efficient than widening to `BigInt`, but on a scale which is hardly significant for this package.)
