### ISSUE TITLE
`about(Memory{Int})` fails

### ISSUE THREAD

**Issue by jakobnissen** [tecosaur/About.jl#7]
```
julia> about(Memory{Int})
Concrete (padded) DataTypeERROR: Type GenericMemory does not have a definite size.
[...]

julia> about(Memory{Int}(undef, 0))
0-element Memory{Int64} (mutable), 0B referencing 16B (<: DenseVector{Int64} <: AbstractVector{Int64} <: Any)
ERROR: Type GenericMemory does not have a definite size.
[...]
```

**Comment by tecosaur** [comment]
I've just pushed 1305239f0165e6192b437837df69e5139d71250c, which makes the type not error. I'm open to providing a nice specialised display though.

```
julia> about(Memory{Int})
Concrete (padded) DataType defined in Core, 
  Memory{Int64} <: DenseVector{Int64} <: AbstractVector{Int64} <: Any

Struct with 2 fields:
• length  Int64       
• ptr     Ptr{Nothing}
```

fixing the memory value case will require some more thought.

**Comment by jakobnissen** [comment]
Related bug: `about(Memory{Int}())` errors.

**Comment by tecosaur** [comment]
Indeed, 

> fixing the memory value case will require some more thought.

:wink: 

Doing the basic fixes can result in this:

```
0-element Memory{Int64} (mutable) (<: DenseVector{Int64} <: AbstractVector{Int64} <: Any)
 Memory footprint: 0B directly (referencing 16B in total)
```

but I do wonder if we could/should do something better.

**Comment by tecosaur** [comment]
I've now got a first attempt:

![image](https://github.com/user-attachments/assets/67df69fb-6ee4-4c92-951a-68f411c1fcd3)

I think there's room for improvement, but it's good enough for an initial release.

**Comment by tecosaur** [comment]
Here we go, I've now got a second attempt:

![image](https://github.com/user-attachments/assets/2c089bc5-743e-4802-91af-fe345a545d50)
